name: shortener
description: "Zero SPOF shortener - Create a short URL that point to a long text."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  ndk: ^0.7.1-dev.19
  ndk_flutter: ^0.0.2-dev.13
  nostr_shortener:
    path: packages/nostr_shortener
  share_plus: ^12.0.1
  system_theme: ^3.2.0
  toastification: ^3.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
